### ISSUE TITLE
GDB python uses wrong paths

### ISSUE THREAD

**Issue by csiefer2** [Char-Aznable/GDBKokkos#2]
```
(gdb) py import GDBKokkos
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/ascldap/users/csiefer/test-gdb-kokkos/GDBKokkos/GDBKokkos/__init__.py", line 10, in <module>
    from GDBKokkos.printView import(
  File "/ascldap/users/csiefer/test-gdb-kokkos/GDBKokkos/GDBKokkos/printView.py", line 19
    def getKokkosViewExtent(view : gdb.Value):
                                 ^
SyntaxError: invalid syntax
Error while executing Python code.

```

Ideas?

**Comment by Char-Aznable** [comment]
What does `(gdb) py import sys; print (sys.version)` say? I guess this is due to gdb invoking python 2 while the module requiring python 3. Function annotation should have worked in early versions of python 3

**Comment by csiefer2** [comment]
Yeah, looks like I forgot to load the right python. Oops.  Now I have:

```
[GCC 7.3.0]
(gdb) py import GDBKokkos
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/ascldap/users/csiefer/test-gdb-kokkos/GDBKokkos/GDBKokkos/__init__.py", line 10, in <module>
    from GDBKokkos.printView import(
  File "/ascldap/users/csiefer/test-gdb-kokkos/GDBKokkos/GDBKokkos/printView.py", line 12, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Error while executing Python code.
```

But numpy *is* installed in my local pip site-packages for 3.8.6

**Comment by DavidPoliakoff** [comment]
Try the same debugging command Char listed above, see if you get 3.8.6

**Comment by csiefer2** [comment]
Sorry.  Meant to copy paste that above

```
(gdb)  py import sys; print (sys.version)
3.8.6 (default, Apr 14 2021, 14:08:00) 
[GCC 7.3.0]
```

**Comment by Char-Aznable** [comment]
This could happens if multiple installations of python coexist and the pip install was accidentally picking up some other python installation's import path than the one GDB is using. To find out, try:
1. Inside gdb, do `(gdb)  py import sys; print (sys.path)`. This should show a list of paths in the order where the `import ` command search for the module (see https://docs.python.org/3/tutorial/modules.html#the-module-search-path for an explanation) 
2. Run the python 3.8.6 which you think you had numpy installed as `python -c "import numpy as np; print(np.__path__)"` 
3. Check if the list of paths in 1 contains the path in 2 (most likely the answer is no and hence the error)
4. If 3 is no, then you can try `PYTHONPATH=/path/to/site-packages gdb` to run gdb, where `/path/to/site-packages` is the parent path of 2 (omitting the `/numpy` in the end).

I would suggest the user using conda enviornment to manage their python packages. This repo has a https://github.com/Char-Aznable/GDBKokkos/blob/master/environment.yml that you can just install with conda to set up a environment with gdb and a python with all the require packages to use GDBKokkos.

**Comment by csiefer2** [comment]
GDB won't find any of the pip stuff unless I manually add it to PYTHONPATH. Ugh.

**Comment by csiefer2** [comment]
I have to manually add the pip site-packages to the PYTHONPATH, but at least now GDBKokkos can get imported...

OK.  Seems to work now.

**Comment by Char-Aznable** [comment]
Great! What do people feel about using conda? I can add a description to the readme

**Comment by csiefer2** [comment]
Finally got it to run.  Ugh.  Python/GDB interaction is terrible.
